site_name: 'cicd'
site_description: 'Main documentation for the cicd'
repo_url: https://github.com/mallama-org/cicd
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting started: 'docs/index.md'